
export const metadata= {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header 
        style={{
          padding: "20px", backgroundColor: "lightblue"
          }}
          >
            <p> This is Header</p>
        </header>
        {children}
        <footer
        style={{
          padding: "20px", backgroundColor: "lightgrey", marginTop: "20px"
          }}
        >
            <p> This is Footer</p>
        </footer>
      </body>
    </html>
  );
}
